name: cmake-build-test
description: Runs cmake configure, build and test

inputs:
  preset:
    description: cmake configure-preset to use
    required: true
  sonar:
    description: whether to add the sonar build wrapper
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Cmake Configure ${{ inputs.preset }}
      working-directory: recorder
      shell: pwsh
      run: cmake --preset ${{ inputs.preset }}

    - name: Cmake Build
      if: "!inputs.sonar "
      working-directory: recorder/build/${{ inputs.preset }}
      shell: pwsh
      run: cmake --build ./build/${{ inputs.preset }}

    - name: Cmake Build (sonar wrapped)
      shell: pwsh
      working-directory: recorder #required for sonar-wrapper values to work correctly
      if: inputs.sonar
      run: ${{ env.SONAR_WRAPPER }}) cmake --build ./build/${{ inputs.preset }}

    - name: CTest
      working-directory: recorder/build/${{ inputs.preset }}
      shell: pwsh
      run: ctest --verbose
