name: cmake-build-test
description: Runs cmake configure, build and test

inputs:
  preset:
    description: cmake configure-preset to use
    required: true
  sonar-wrapper:
    description: optional sonar-wrapper for publishing test results
    required: false
    default: ""


runs:
  using: "composite"
  steps:
    - name: Cmake Configure ${{ inputs.preset }}
      shell: pwsh
      working-directory: recorder
      run: |
        cmake --preset ${{ inputs.preset }}

    - name: Cmake Build
      shell: pwsh
      if: ${{ matrix.build-preset == '' }}
      working-directory: recorder #required for sonar-wrapper values to work correctly
      run: |
        ${{ inputs.sonar-wrapper }} cmake --build ./build/${{ inputs.preset }}

    - name: CTest
      shell: pwsh
      working-directory: recorder/build/${{ inputs.preset }}
      run: |
        ctest --verbose
