name: prepare-vcpkg-cmake
description: Prepares the host for building with vcpkg and cmake (incl. ninja)

inputs:
  nuget_cmd_prefix:
    description: To run `nuget.exe` on non-Windows platforms, we must use `mono`.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: "Create directory '${{ inputs.vcpkg_default_cache }}'"
      run: mkdir -p ${{ inputs.vcpkg_default_cache }}
      shell: bash

    # Setup the build machine with the most recent versions of CMake and Ninja.
    # Both are cached if not already: on subsequent runs both will be quickly restored from GitHub cache service.
    - uses: lukka/get-cmake@latest
      # with:
      #   cmakeVersion: 3.25.2     # <--= optional, stick to exactly 3.25.2 version
      #   ninjaVersion: 1.11.1     # <--= optional, stick to exactly 1.11.1 version

    - name: "Setup NuGet Credentials"
      shell: pwsh
      run: |
        ${{ inputs.nuget_cmd_prefix }} `./recorder/vcpkg/vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/{{ github.repository_owner }}/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "{{ github.repository_owner }}" \
          -password "${{ secrets.GITHUB_TOKEN }}"
        ${{ inputs.nuget_cmd_prefix }} `./recorder/vcpkg/vcpkg fetch nuget | tail -n 1` \
          setapikey "${{ secrets.GITHUB_TOKEN }}" \
          -source "https://nuget.pkg.github.com/{{ github.repository_owner }}/index.json"
