name: prepare-vcpkg-cmake
description: Prepares the host for building with vcpkg and cmake (incl. ninja)

inputs:
  github_token:
    description: workflow auth token (https://docs.github.com/en/actions/security-guides/automatic-token-authentication)
    required: true
  nuget_cmd_prefix:
    description: To run `nuget.exe` on non-Windows platforms, we must use `mono`.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    # Setup the build machine with the most recent versions of CMake and Ninja.
    - uses: lukka/get-cmake@latest
      # with:
      #   cmakeVersion: 3.25.2     # <--= optional, stick to exactly 3.25.2 version
      #   ninjaVersion: 1.11.1     # <--= optional, stick to exactly 1.11.1 version

    - name: "DEBUGSTEP"
      shell: "pwsh"
      working-directory: recorder
      run: vcpkg/vcpkg

    - name: "Setup NuGet Credentials"
      shell: "bash"
      working-directory: recorder
      run: |
        ${{ inputs.nuget_cmd_prefix }} `./vcpkg/vcpkg.exe fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "${{ github.repository_owner }}" \
          -password "${{ inputs.github_token }}"
        ${{ inputs.nuget_cmd_prefix }} `./vcpkg/vcpkg fetch nuget | tail -n 1` \
          setapikey "${{ inputs.github_token }}" \
          -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
