name: prepare-vcpkg
description: Bootstraps vcpkg and registers nuget cache

inputs:
  github_token:
    description: workflow auth token (https://docs.github.com/en/actions/security-guides/automatic-token-authentication)
    required: true

runs:
  using: "composite"
  steps:
    - name: Bootstrap vcpkg
      working-directory: recorder/vcpkg
      shell: pwsh
      run: |
        if($env:RUNNER_OS -eq 'Windows'){ ./bootstrap-vcpkg.bat }
        if($env:RUNNER_OS -eq 'Linux'){ ./bootstrap-vcpkg.sh }

    - name: Windows prep
      if: runner.os == 'Windows'
      working-directory: recorder/vcpkg
      shell: pwsh
      run: ./bootstrap-vcpkg.bat

    - name: "Setup NuGet Credentials"
      shell: pwsh
      working-directory: recorder/vcpkg
      run: |
        $source = "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        $nuget_cmd_prefix = ''
        if($env:RUNNER_OS -eq 'Linux'){ $nuget_cmd_prefix = 'mono' }
        ./vcpkg fetch nuget
        $nuget_exe = ./vcpkg fetch nuget
        & "$nuget_cmd_prefix $nuget_exe" sources add -source $source -storepasswordincleartext -name "GitHub" -username "${{ github.repository_owner }}" -password "${{ inputs.github_token }}"
        & "$nuget_cmd_prefix $nuget_exe" setapikey "${{ inputs.github_token }}" -source $source
