name: setup-linux-tools
description: Setup of needed linux build tooling

inputs:
  clang:
    description: whether to install clang compiler and tools
    required: false
  gcc:
    description: version to be install gcc compiler
    required: false
  sonar:
    description: whether to run sonar cloud analysis
    required: false
  gcov:
    description: whether to collect coverage data via gcov
    required: false

runs:
  using: "composite"
  steps:
    - name: install gcc
      if: ${{ inputs.gcc }}
      uses: egor-tensin/setup-gcc@v1
      with:
        version: ${{ env.GCC_VERSION }}
        platform: x64

    - name: install clang
      if: inputs.clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: ${{ env.CLANG_VERSION }} # ignored on windows
        platform: x64

    - name: install clang-tidy
      shell: bash
      if: inputs.clang
      run: sudo apt-get install -y clang-tidy-${{ env.CLANG_VERSION }}

    - name: setup clang-tidy path
      shell: bash
      if: inputs.clang
      run: |
        for f in clang++ clang-tidy; do # ?? is it really needed to also touch the clang++ path?
          if [ -e /usr/bin/${f} ]; then sudo unlink /usr/bin/${f}; fi
          sudo ln -s /usr/bin/${f}-${{ env.CLANG_VERSION }} /usr/bin/${f}
        done

    - name: Set up Python 3.8 for gcovr
      uses: actions/setup-python@v4
      if: inputs.gcov
      with:
        python-version: 3.8

    - name: install gcovr 5.0
      if: inputs.gcov
      shell: pwsh
      run: |
        pip install gcovr==5.0

    - name: Install sonar-scanner and build-wrapper
      if: inputs.sonar
      uses: SonarSource/sonarcloud-github-c-cpp@v1
