# workflow that builds the linux-dev image and uploads it to some container registry

name: linux dev image
on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: "Version tag"
        required: true
        default: "latest"
        type: string
      gcc-version:
        description: "Gcc version"
        required: true
        type: string
        default: "12"
      clang-version:
        description: "Clang version (incl. llvm and clang tooling)"
        required: true
        type: string
        default: "15"

env:
  IMAGE_FILE: "linux-dev.Dockerfile"
  GAR_LOCATION: "europe-west3"
  GAR_PROJECT: "arena-385320"
  GAR_REPOSITORY: "recorder"
  GCLOUD_SERVICE_ACCOUNT: "github-workflows"
  GCLOUD_WORKLOAD_ID_PROVIDER: "projects/1070825474922/locations/global/workloadIdentityPools/github-id-pool/providers/github-id-pool-provider"

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: "actions/checkout@v3"

      - name: Save image tag
        run: echo "IMAGE_TAG=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GAR_PROJECT}}/${{ env.GAR_REPOSITORY }}/linux-dev:${{ inputs.version-tag }}" >> $GITHUB_ENV

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v1.1.0"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ env.GCLOUD_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ env.GCLOUD_SERVICE_ACCOUNT }}@${{ env.GAR_PROJECT }}.iam.gserviceaccount.com
          access_token_lifetime: 3600s

      - id: "login"
        name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Docker build
        shell: pwsh
        working-directory: .devcontainer
        run: >
          docker build
          --file ${{ env.IMAGE_FILE }}
          --tag ${{ env.IMAGE_TAG }}
          --build-arg CLANG_VERSION=${{ inputs.clang-version }}
          --build-arg GCC_VERSION=${{ inputs.gcc-version }}
          --label=clang-version-${{ inputs.clang-version }}
          --label=gcc-version-${{ inputs.gcc-version }}
          .

      - name: Docker push
        shell: pwsh
        run: docker push ${{ env.IMAGE_TAG }}
