# workflow that builds the linux-dev image and uploads it to some container registry

name: linux dev image
on: workflow_dispatch

env:
  IMAGE: "linux-dev.Dockerfile"
  GAR_LOCATION: "europe-west3"
  GAR_PROJECT: "arena-385320"
  GAR_REPOSITORY: "recorder"

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v1.1.0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CLOUD_KEY }}"
          # token_format: "access_token"

      # - id: "login"
      #   name: Login to GAR
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
      #     username: "oauth2accesstoken"
      #     password: "${{ steps.auth.outputs.access_token }}"

      - name: Docker build
        shell: pwsh
        working-directory: .devcontainer
        run: docker build -f ${{ env.IMAGE }} -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GAR_PROJECT}}/${{ env.GAR_REPOSITORY }}/linux-dev:latest .

      - name: Docker push
        shell: pwsh
        run: docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GAR_PROJECT}}/${{ env.GAR_REPOSITORY }}/linux-dev:latest
