# CI workflow that builds and tests the code on different os and compilers
# relies on the CMakePresets.json entries

# inspired by / adapted from:
# https://github.com/lukka/CppCMakeVcpkgTemplate/blob/main/.github/workflows/hosted-pure-workflow.yml

name: ci (recorder)
on:
  schedule:
    - cron: "25 16 * * *"
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

env:
  VS_VERSION: 2022
  CLANG_VERSION: 15
  GCC_VERSION: 12

jobs:
  ci-linux:
    name: ${{ matrix.os }} (${{ matrix.cmake-preset }})
    env:
      SONAR_WRAPPER: build-wrapper-linux-x86-64 --out-dir ./build-wrapper-output
      SONAR_ARGS: >
        --define sonar.cfamily.build-wrapper-output=recorder/build-wrapper-output
        --define sonar.coverageReportPaths=coverage.xml
      # TO BE REMOVED:
      INSTALL_GCC_VERSION: 12
      INSTALL_CLANG_VERSION: -1

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

        cmake-preset:
          - gcc-debug-coverage

        # used to compose a 'vcpkg-triplet-like' label for the cache key (see below)
        platform:
          - x64

        include:
          - os: ubuntu-latest
            cmake-preset: gcc-debug-coverage
            coverage: true
            sonar-wrapper: build-wrapper-linux-x86-64 --out-dir ./build-wrapper-output
            sonar-args: >
              --define sonar.cfamily.build-wrapper-output=recorder/build-wrapper-output
              --define sonar.coverageReportPaths=coverage.xml

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0 # vcpkg submodule uses ''baseline', which requires full git history
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Prepare vcpkg, cmake and ninja
        uses: "./.github/prepare-vcpkg-cmake"
        with:
          os: windows
          platform: x64
          vcpkg_root: ${{ github.workspace }}/recorder/vcpkg
          vcpkg_default_cache: ${{ github.workspace }}/recorder/vcpkg/bincache

      - name: install gcc
        if: ${{ env.INSTALL_GCC_VERSION > 0 && contains(matrix.cmake-preset, 'gcc') }}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ env.INSTALL_GCC_VERSION }}
          platform: x64

      - name: install clang
        if: ${{ env.INSTALL_CLANG_VERSION > 0 && contains(matrix.cmake-preset, 'clang') }}
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ env.INSTALL_CLANG_VERSION }} # ignored on windows
          platform: x64

      - name: install clang-tidy
        shell: bash
        if: ${{ env.INSTALL_CLANG_VERSION > 0 && contains(matrix.cmake-preset, 'clang') && contains(matrix.os, 'ubuntu')}}
        run: sudo apt-get install -y clang-tidy-${{ env.DESIRED_CLANG_VERSION }}

      - name: setup clang-tidy path
        shell: bash
        if: ${{ env.INSTALL_CLANG_VERSION > 0 && contains( matrix.cmake-preset, 'clang') && contains(matrix.os, 'ubuntu')}}
        run: |
          for f in clang++ clang-tidy; do # ?? is it really needed to also touch the clang++ path?
            if [ -e /usr/bin/${f} ]; then sudo unlink /usr/bin/${f}; fi
            sudo ln -s /usr/bin/${f}-${{ env.DESIRED_CLANG_VERSION }} /usr/bin/${f}
          done

      - name: install gcovr
        if: matrix.coverage
        shell: pwsh
        run: sudo apt install gcovr

      - name: Install sonar-scanner and build-wrapper
        if: ${{ matrix.sonar-wrapper != '' }}
        uses: SonarSource/sonarcloud-github-c-cpp@v1

      - name: Cmake Configure ${{ matrix.cmake-preset }}
        working-directory: recorder
        shell: pwsh
        run: |
          cmake --preset ${{ matrix.cmake-preset }}

      - name: Cmake Build
        if: ${{ matrix.build-preset == '' }}
        working-directory: recorder #required for matrix.sonar-wrapper values to work
        shell: pwsh
        run: |
          ${{ matrix.sonar-wrapper }} cmake --build ./build/${{ matrix.cmake-preset }} --verbose

      - name: Cmake Build (preset ${{ matrix.build-preset }})
        if: ${{ matrix.build-preset != '' }}
        working-directory: recorder #required for matrix.sonar-wrapper values to work
        shell: pwsh
        run: |
          ${{ matrix.sonar-wrapper }} cmake --build --preset ${{ matrix.build-preset }}

      - name: Run CTest ${{ matrix.cmake-preset }}
        if: ${{ matrix.test-preset == '' }}
        working-directory: recorder/build/${{ matrix.cmake-preset }}
        shell: pwsh
        run: |
          ctest --verbose

      - name: Run CTest (preset ${{ matrix.test-preset }})
        if: ${{ matrix.test-preset != '' }}
        working-directory: recorder
        shell: pwsh
        run: |
          ctest --preset ${{ matrix.test-preset }}

      - name: Collect coverage into one XML report
        if: ${{ matrix.coverage }}
        shell: pwsh
        run: gcovr --verbose --sonarqube --exclude-unreachable-branches --output coverage.xml

      - name: Coverage report debug info
        if: matrix.coverage
        shell: pwsh
        run: |
          Write-Host "gcovr version: $(gcovr --version)"
          Write-Host "listing .gcno and .gcda files:"
          Get-ChildItem -Path .\ -Filter *.gcno -Recurse -File -Name
          Get-ChildItem -Path .\ -Filter *.gcda -Recurse -File -Name
          Write-Host "Content of 'coverage.xml':"
          Get-Content coverage.xml

      - name: Run sonar-scanner
        if: ${{ matrix.sonar-wrapper != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          sonar-scanner ${{ matrix.sonar-args }}
