# CI workflow that builds and tests the code on different os and compilers
# relies on the CMakePresets.json entries

# inspired by / adapted from:
# https://github.com/lukka/CppCMakeVcpkgTemplate/blob/main/.github/workflows/hosted-pure-workflow.yml

name: ci (recorder)
on:
  schedule:
    - cron: '25 16 * * *'
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  ci-windows:
    name: ${{ matrix.os }} (${{ matrix.cmake-preset }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        cmake-preset:
          - x64-msvc-release
          - x64-msvc-debug
          - x64-clang-cl-release-tidy

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0 # vcpkg submodule uses ''baseline', which requires full git history
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Prepare vcpkg, cmake and ninja
        uses: "./.github/prepare-vcpkg-cmake"
        with:
          os: windows
          platform: x64
          vcpkg_default_cache: ${{ github.workspace }}/recorder/vcpkg
          vcpkg_root-wrapper: ${{ github.workspace }}/recorder/vcpkg/bincache

      # Set VS Developer Command Prompt targeting x64
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Cmake build and test
        uses: "./.github/cmake-build-test"
        with:
          preset: ${{ matrix.cmake-preset }}

  ci-linux:
    name: ${{ matrix.os }} (${{ matrix.cmake-preset }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

        cmake-preset:
          - gcc-release
          - gcc-debug-coverage
          - clang-debug
          - clang-release-tidy

        include:
          - os: ubuntu-latest
            cmake-preset: gcc-debug-coverage
            coverage: true
            sonar-wrapper: build-wrapper-linux-x86-64 --out-dir ./build-wrapper-output
            sonar-args: >
              --define sonar.cfamily.build-wrapper-output=recorder/build-wrapper-output
              --define sonar.coverageReportPaths=coverage.xml

    env:
      GCC_VERSION: 12
      CLANG_VERSION: 15

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0 # vcpkg submodule uses ''baseline', which requires full git history
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Prepare vcpkg, cmake and ninja
        uses: "./.github/prepare-vcpkg-cmake"
        with:
          os: windows
          platform: x64
          vcpkg_default_cache: ${{ github.workspace }}/recorder/vcpkg
          vcpkg_root-wrapper: ${{ github.workspace }}/recorder/vcpkg/bincache

      - name: Setup linux tools
        uses: "./.github/setup-linux-tools"
        with:
          clang-version: ${{ env.CLANG_VERSION }}
          gcc-version: ${{ env.GCC_VERSION }}
          gcov: ${{ matrix.coverage }}
          sonar: ${{ matrix.sonar-wrapper != '' }}

      - name: Cmake build and test
        uses: "./.github/cmake-build-test"
        with:
          preset: ${{ matrix.cmake-preset }}
          sonar-wrapper: ${{ matrix.sonar-wrapper }}

      - name: Collect coverage into one XML report
        if: ${{ matrix.coverage }}
        shell: pwsh
        run: gcovr --sonarqube > coverage.xml

      - name: Run sonar-scanner
        if: ${{ matrix.sonar-wrapper != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: >
          sonar-scanner
          --define sonar.cfamily.build-wrapper-output=recorder/build-wrapper-output
          --define sonar.coverageReportPaths=coverage.xml


  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: clang-format src
      if: ${{ always() }}
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '15'
        check-path: 'recorder/src'
        # exclude: '(hello|world)' # Exclude file paths containing "hello" or "world"
        exclude-regex: ''
    - name: clang-format test
      if: ${{ always() }}
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '15'
        check-path: 'recorder/test'
        exclude-regex: ''
