# CI workflow that builds and tests the code on different os and compilers
# relies on the CMakePresets.json entries

# inspired by / adapted from:
# https://github.com/lukka/CppCMakeVcpkgTemplate/blob/main/.github/workflows/hosted-pure-workflow.yml

name: ci (recorder)
on:
  schedule:
    - cron: "25 16 * * *"
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

env:
  VS_VERSION: 2022
  CLANG_VERSION: 15
  GCC_VERSION: 12

jobs:
  ci-linux:
    name: ${{ matrix.os }} (${{ matrix.cmake-preset }})
    env:
      SONAR_WRAPPER: build-wrapper-linux-x86-64 --out-dir ./build-wrapper-output
      SONAR_ARGS: >
        --define sonar.cfamily.build-wrapper-output=recorder/build-wrapper-output
        --define sonar.coverageReportPaths=coverage.xml
      # TO BE REMOVED:
      VCPKG_ROOT: ${{ github.workspace }}/recorder/vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/recorder/vcpkg/bincache

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

        cmake-preset:
          - gcc-debug-coverage

        # used to compose a 'vcpkg-triplet-like' label for the cache key (see below)
        platform:
          - x64

        include:
          - os: ubuntu-latest
            cmake-preset: gcc-debug-coverage
            coverage: true
            sonar: true

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0 # vcpkg submodule uses ''baseline', which requires full git history
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Prepare vcpkg, cmake and ninja
        uses: "./.github/prepare-vcpkg-cmake"
        with:
          os: windows
          platform: x64
          vcpkg_root: ${{ github.workspace }}/recorder/vcpkg
          vcpkg_default_cache: ${{ github.workspace }}/recorder/vcpkg/bincache

      - name: Setup linux tools
        uses: "./.github/setup-linux-tools"
        with:
          clang: ${{ contains(matrix.cmake-preset, 'clang') }}
          gcc: ${{ contains(matrix.cmake-preset, 'gcc') }}
          gcov: ${{ matrix.coverage }}
          sonar: ${{ matrix.sonar }}

      - name: Cmake Configure ${{ matrix.cmake-preset }}
        working-directory: recorder
        shell: pwsh
        run: |
          cmake --preset ${{ matrix.cmake-preset }}

      - name: Cmake Build
        if: ${{ matrix.build-preset == '' }}
        working-directory: recorder #required for matrix.sonar-wrapper values to work
        shell: pwsh
        run: |
          ${{ matrix.sonar-wrapper }} cmake --build ./build/${{ matrix.cmake-preset }}

      - name: Cmake Build (preset ${{ matrix.build-preset }})
        if: ${{ matrix.build-preset != '' }}
        working-directory: recorder #required for matrix.sonar-wrapper values to work
        shell: pwsh
        run: |
          ${{ matrix.sonar-wrapper }} cmake --build --preset ${{ matrix.build-preset }}

      - name: Run CTest ${{ matrix.cmake-preset }}
        if: ${{ matrix.test-preset == '' }}
        working-directory: recorder/build/${{ matrix.cmake-preset }}
        shell: pwsh
        run: |
          ctest --verbose

      - name: Run CTest (preset ${{ matrix.test-preset }})
        if: ${{ matrix.test-preset != '' }}
        working-directory: recorder
        shell: pwsh
        run: |
          ctest --preset ${{ matrix.test-preset }}

      - name: Collect coverage into one XML report
        if: matrix.coverage
        working-directory: recorder/build/${{ matrix.cmake-preset }}
        shell: pwsh
        run: gcovr --verbose --sonarqube --exclude-unreachable-branches --output ${{ github.workspace }}/coverage.xml --root ${{ github.workspace }}

      - name: Coverage report debug info
        if: matrix.coverage
        shell: pwsh
        run: |
          Write-Host "gcovr version: $(gcovr --version)"
          Write-Host "listing .gcno and .gcda files:"
          Get-ChildItem -Path .\ -Filter *.gcno -Recurse -File -Name
          Get-ChildItem -Path .\ -Filter *.gcda -Recurse -File -Name
          Write-Host "Content of 'coverage.xml':"
          Get-Content coverage.xml

      - name: Run sonar-scanner
        if: matrix.sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: sonar-scanner ${{ env.SONAR_ARGS }}
